

export const metadata = {
  // TODO: meta image com os dizeres do pingo - talvez de forma dinâmica pelo cloudinary
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
